#!/bin/bash

# Define output directory and file
OUTPUT_DIR="/wrccdc/user_passwords"
OUTPUT_FILE="$OUTPUT_DIR/$(hostname)-new_passwords.txt"

# Ensure output directory exists
mkdir -p "$OUTPUT_DIR"

# Function to generate a random password
generate_password() {
    local length=$1
    tr -dc 'A-Za-z0-9!@#$%^&*()_+{}|:<>?=' < /dev/urandom | head -c $length
}

# Get list of users with UID >= 1000 and < 6000
users=$(awk -F: '$3 >= 1000 && $3 < 6000 {print $1}' /etc/passwd)

# Initialize an associative array to store user passwords
declare -A user_passwords

# Generate a new password for each user
for user in $users; do
    user_passwords[$user]=$(generate_password 16)
done

# Change password for each user
for user in "${!user_passwords[@]}"; do
    echo "${user}:${user_passwords[$user]}" | chpasswd
done

# Prepare content for password file
password_file_content=""
for user in "${!user_passwords[@]}"; do
    password_file_content+="User: $user, Password: ${user_passwords[$user]}\n"
done

# Write passwords to file
echo -e "$password_file_content" > "$OUTPUT_FILE"
chmod 0777 "$OUTPUT_FILE"

echo "Passwords have been changed and saved to $OUTPUT_FILE"